project_id = "edeprzdcvbejtnhoqawv"

[functions.check-late-arrivals]
verify_jwt = false

[functions.bootstrap-role]
verify_jwt = false

[functions.generate-recurring-jobs]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.invite-staff]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false
