project_id = "edeprzdcvbejtnhoqawv"

[functions.check-late-arrivals]
verify_jwt = false

[functions.bootstrap-role]
verify_jwt = false

[functions.generate-recurring-jobs]
verify_jwt = false

[functions.send-email]
verify_jwt = false